name: Databricks pipeline

on:
  push:
    branches: ["main"]

env:
  DATABRICKS_CLIENT_ID: ${{secrets.DATABRICKS_CLIENT_ID}}
  DATABRICKS_CLIENT_SECRET: ${{secrets.DATABRICKS_CLIENT_SECRET}}
  PROD_DIRECTORY: "/Repos/GA/cicd_w_dabs_ga_demo"

jobs: 

  deploy:
    name: Deploy bundle
    runs-on: windows-latest


    environment: stu_prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install --upgrade "databricks-cli>=0.205"

      - name: Deploy bundle
        run: databricks bundle deploy --target prod
        env:
          DATABRICKS_BUNDLE_ENV: prod

  
